[project]
name = "ab-dev-patents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-cloud-bigquery>=3.42.3",
    "google-cloud-bigquery-storage>=2.39.0",
    "google-genai>=2.16.0",
    "polars>=1.43.2",
    "pydantic>=2.0",
    "pyarrow>=25.0.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupytext>=1.19.5",
]
