"""Data file locations.

raw/       downloaded or paid-for source data; not regenerated by a rerun
interim/   derived from raw/ by a script
"""

from __future__ import annotations

from pathlib import Path

DATA = Path(__file__).resolve().parents[2] / "data"

RAW = DATA / "raw"
INTERIM = DATA / "interim"

# raw
EBI = RAW / "ebi_uspto.parquet"  # patent protein sequences, keyed (patent, seq_id)
HTML = RAW / "fulltext_html.parquet"  # description HTML for EBI-covered antibody patents

# interim
MEASUREMENTS = INTERIM / "measurements_html.parquet"
TRAINING = INTERIM / "training_html.parquet"
